controlnet extension - few compat fixes
lllyasviel/stable-diffusion-webui-forge pull request #474
Opened 2024-03-03 12:33 UTC by light-and-ray

In support forge in my extension I've faced external_code no longer has `to_processing_unit`. And also it produces errors if few units are None

## Checklist:

- [x] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [x] I have performed a self-review of my own code
- [x] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [x] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

2024-03-04 03:35 UTC, RubenBernardezHernande133z requested changes
Hastalapolla

2024-03-04 04:12 UTC, huchenlei reviewed
I don't think the changes here are well justified. 
- For `to_processing_unit`, can you share the code which call `to_processing_unit`?
  - As no code in this repo actually calls `to_processing_unit`, I think you can implement it in your code, instead of adding the logic here.
- For `None` filter, can you provide the code path that `None` could be passed as ControlNet's script args?

2024-03-09 01:49 UTC, huchenlei approved these changes
waiting for @lllyasviel's review

2024-08-01 19:52 UTC, closed without merging

2024-08-01 19:52 UTC, lllyasviel commented
hi we are going to close PRs before forge's recent major revision
if we missed some important PRs, please consider reopen (if that is not already on our todo list