Add cos xl
lllyasviel/stable-diffusion-webui-forge pull request #710
Opened 2024-05-06 07:20 UTC by GavChap

## Description

* Add support for cosxl and other vpred EDM checkpoints
* Added code to sort the above
* 
## Checklist:

- [ x] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [x ] I have performed a self-review of my own code
- [x ] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [ x] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

2024-05-22 21:46 UTC, huchenlei requested changes
Can you add a short summary of how to use this new feature? e.g. where to download checkpoints, and steps with screenshots of GUI to use the feature.

2024-05-23 20:22 UTC, GavChap commented
> Can you add a short summary of how to use this new feature? e.g. where to download checkpoints, and steps with screenshots of GUI to use the feature.

Done.

2024-05-23 20:42 UTC, huchenlei approved these changes

2024-05-23 20:42 UTC, merged

2024-10-20 16:40 UTC, Enferlain commented
did this break in the previous updates since then? k_prediction.py has all the types but they don't seem to do anything